//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pokedexEntities : DbContext
    {
        public pokedexEntities()
            : base("name=pokedexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<evolucion> evolucions { get; set; }
        public virtual DbSet<habilidad> habilidads { get; set; }
        public virtual DbSet<juego> juegos { get; set; }
        public virtual DbSet<juegosrelacion> juegosrelacions { get; set; }
        public virtual DbSet<logdata> logdatas { get; set; }
        public virtual DbSet<move> moves { get; set; }
        public virtual DbSet<movesrelacion> movesrelacions { get; set; }
        public virtual DbSet<pokemon> pokemons { get; set; }
        public virtual DbSet<stat> stats { get; set; }
        public virtual DbSet<tipo> tipoes { get; set; }
        public virtual DbSet<tiporelacion> tiporelacions { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    
        public virtual ObjectResult<ActiveUsers_Month_Result> ActiveUsers_Month()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActiveUsers_Month_Result>("ActiveUsers_Month");
        }
    
        public virtual ObjectResult<ActiveUsers_Week_Result> ActiveUsers_Week()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActiveUsers_Week_Result>("ActiveUsers_Week");
        }
    
        public virtual int CreateAbility(string name, string description)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateAbility", nameParameter, descriptionParameter);
        }
    
        public virtual int CreateEvolution(Nullable<int> pokeID, Nullable<int> sigID, Nullable<int> antID, string status, string descripcion)
        {
            var pokeIDParameter = pokeID.HasValue ?
                new ObjectParameter("PokeID", pokeID) :
                new ObjectParameter("PokeID", typeof(int));
    
            var sigIDParameter = sigID.HasValue ?
                new ObjectParameter("SigID", sigID) :
                new ObjectParameter("SigID", typeof(int));
    
            var antIDParameter = antID.HasValue ?
                new ObjectParameter("AntID", antID) :
                new ObjectParameter("AntID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateEvolution", pokeIDParameter, sigIDParameter, antIDParameter, statusParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<GetLoginDays_Result> GetLoginDays()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLoginDays_Result>("GetLoginDays");
        }
    
        public virtual ObjectResult<GetLoginHours_Result> GetLoginHours()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLoginHours_Result>("GetLoginHours");
        }
    
        public virtual int GetSPByHour(Nullable<System.DateTime> date1, Nullable<System.DateTime> date2)
        {
            var date1Parameter = date1.HasValue ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(System.DateTime));
    
            var date2Parameter = date2.HasValue ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSPByHour", date1Parameter, date2Parameter);
        }
    
        public virtual ObjectResult<GetUserContains_Result> GetUserContains(string patron)
        {
            var patronParameter = patron != null ?
                new ObjectParameter("patron", patron) :
                new ObjectParameter("patron", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserContains_Result>("GetUserContains", patronParameter);
        }
    
        public virtual ObjectResult<GetUserSubtotals_Result> GetUserSubtotals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserSubtotals_Result>("GetUserSubtotals");
        }
    
        public virtual ObjectResult<InactiveUsers_Month_Result> InactiveUsers_Month()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InactiveUsers_Month_Result>("InactiveUsers_Month");
        }
    
        public virtual ObjectResult<MyActiveUsers_Month_Result> MyActiveUsers_Month()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MyActiveUsers_Month_Result>("MyActiveUsers_Month");
        }
    
        public virtual ObjectResult<SPByUser_Result> SPByUser(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPByUser_Result>("SPByUser", useridParameter);
        }
    
        public virtual ObjectResult<SPCount_Result> SPCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPCount_Result>("SPCount");
        }
    
        public virtual ObjectResult<SPExecAverage_Result> SPExecAverage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPExecAverage_Result>("SPExecAverage");
        }
    
        public virtual ObjectResult<SPInRange_Result> SPInRange(Nullable<int> lowlimit, Nullable<int> highlimit)
        {
            var lowlimitParameter = lowlimit.HasValue ?
                new ObjectParameter("lowlimit", lowlimit) :
                new ObjectParameter("lowlimit", typeof(int));
    
            var highlimitParameter = highlimit.HasValue ?
                new ObjectParameter("highlimit", highlimit) :
                new ObjectParameter("highlimit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPInRange_Result>("SPInRange", lowlimitParameter, highlimitParameter);
        }
    }
}
