//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat
    {
        public int StatID { get; set; }
        public int PokeID { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> Attack { get; set; }
        public Nullable<int> Defense { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> SplAttack { get; set; }
        public Nullable<int> SplDefense { get; set; }
    }
}
