//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokedexFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int PokemonID { get; set; }
        public string Nombre { get; set; }
        public int Peso { get; set; }
        public double Altura { get; set; }
        public int Generacion { get; set; }
        public int TpID { get; set; }
        public Nullable<int> TpID2 { get; set; }
        public Nullable<int> HabID { get; set; }
        public string pathImg { get; set; }
    }
}
