CREATE DATABASE Pokedex
USE Pokedex
CREATE TABLE Pokemon(
	PokemonID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(20) NOT NULL,
	Peso INT NOT NULL,
	Altura FLOAT NOT NULL,
	Generacion INT NOT NULL,
	TipoID INT NOT NULL,
	TipoID2 INT,
	HabilidadID INT
)

CREATE TABLE Stat(
	StatID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PokemonID INT NOT NULL,
	HP INT,
	Attack INT,
	Defense INT,
	Speed INT,
	SplAttack INT,
	SplDefense INT
)

CREATE TABLE Juegos(
	JuegoID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100),
	Año DATETIME,
	Generacion VARCHAR(10),
	Region VARCHAR(25)
)

CREATE TABLE Tipo(
	TipoID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	Nombre VARCHAR(25)
)

CREATE TABLE Moves(
	MoveID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TipoID INT,
	Nombre VARCHAR(25),
	Accuracy INT,
	[Power] INT,
	PowerPoints INT,
	Generacion INT
)

CREATE TABLE JuegosRelacion(
	JuegoRelID  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PokemonID INT,
	JuegoID INT
)

CREATE TABLE TipoRelacion(
	TipoID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Ventaja VARCHAR(25),
	DetailVentaja VARCHAR(MAX),
	Debilidad VARCHAR(25),
	DetailDebilidad VARCHAR(MAX)
)

CREATE TABLE Evolucion(
	EvolucionID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PokemonID INT NOT NULL,
	AntID INT,
	SigId INT,
	status VARCHAR(MAX),
	descripcion VARCHAR(MAX)
)

CREATE TABLE Habilidad(
	HabilidadID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name VARCHAR(15),
	Descripcion VARCHAR(200)
)

CREATE TABLE MovesRelacion(
	MovRelID INT IDENTITY(1,1) NOT NULL PRIMARY KEY ,
	PokemonID INT, 
	MoveID INT
)

CREATE TABLE Usuario
(
	UserId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100) ,
	Apellido VARCHAR(100),
	email VARCHAR(100),
	DoB DATETIME,
	Username VARCHAR(100),
	[Password] VARCHAR(25),
	[Privileges] VARCHAR(20)
)
CREATE TABLE LogData
(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	nombre VARCHAR(100),
	tipo  VARCHAR(50),
	fecha DATETIME,
	exec_time INT NULL,
	UserId  INT NULL 

)

