//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSQLProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class evolucion
    {
        public int EvolucionID { get; set; }
        public int PokeID { get; set; }
        public Nullable<int> AntID { get; set; }
        public Nullable<int> SigId { get; set; }
        public string status { get; set; }
        public string descripcion { get; set; }
    }
}
