//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSQLProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class move
    {
        public int MoveID { get; set; }
        public Nullable<int> TpMovID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Accuracy { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<int> PowerPoints { get; set; }
        public Nullable<int> Generacion { get; set; }
    }
}
