//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSQLProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiporelacion
    {
        public int TpRelID { get; set; }
        public string Ventaja { get; set; }
        public string DetailVentaja { get; set; }
        public string Debilidad { get; set; }
        public string DetailDebilidad { get; set; }
    }
}
